export const dummyData = [
  {
    name: "James Smith",
    company: "TechNova Ltd",
    mobile_phone: "07 3564 8273",
    email_address: "james.smith@technova.co.uk",
    postcode: "AB12CD",
    pay_later: true,
    pay_now: false,
  },
  {
    name: "Emily Johnson",
    company: "BrightWorks Inc",
    mobile_phone: "07 4523 9811",
    email_address: "emily.j@brightworks.com",
    postcode: "NW18XZ",
    pay_later: false,
    pay_now: true,
  },
  {
    name: "Michael Brown",
    company: "InnoWave Solutions",
    mobile_phone: "07 6245 1389",
    email_address: "m.brown@innowave.io",
    postcode: "E29TY",
    pay_later: false,
    pay_now: false,
  },
  {
    name: "Olivia Davis",
    company: "CoreLogic Systems",
    mobile_phone: "07 3816 9472",
    email_address: "olivia.davis@corelogic.com",
    postcode: "SE145QL",
    pay_later: true,
    pay_now: false,
  },
  {
    name: "William Taylor",
    company: "Skyline Ventures",
    mobile_phone: "07 9382 6610",
    email_address: "will.t@skylineventures.net",
    postcode: "L34DF",
    pay_later: true,
    pay_now: false,
  },
  {
    name: "Sophia Anderson",
    company: "NextGen Systems",
    mobile_phone: "07 4729 3312",
    email_address: "sophia@nextgensystems.co",
    postcode: "M19YZ",
    pay_later: false,
    pay_now: true,
  },
  {
    name: "Benjamin Wilson",
    company: "GreenLeaf Technologies",
    mobile_phone: "07 8241 7736",
    email_address: "bwilson@greenleaf.io",
    postcode: "BS16DJ",
    pay_later: true,
    pay_now: true,
  },
  {
    name: "Isabella Thomas",
    company: "UrbanEdge Group",
    mobile_phone: "07 2154 8739",
    email_address: "isabella.thomas@urbanedge.com",
    postcode: "TN12GH",
    pay_later: false,
    pay_now: false,
  },
  {
    name: "Henry Moore",
    company: "OmniCore Ltd",
    mobile_phone: "07 3652 9147",
    email_address: "henry.moore@omnicore.com",
    postcode: "PE14ZX",
    pay_later: false,
    pay_now: true,
  },
  {
    name: "Mia Jackson",
    company: "BluePeak Ltd",
    mobile_phone: "07 1358 9982",
    email_address: "mia.jackson@bluepeak.org",
    postcode: "GL89OP",
    pay_later: true,
    pay_now: false,
  },
  {
    name: "Alexander White",
    company: "LumaTech Ltd",
    mobile_phone: "07 2947 6381",
    email_address: "a.white@lumatech.co.uk",
    postcode: "WC1E7JL",
    pay_later: true,
    pay_now: false,
  },
  {
    name: "Charlotte Harris",
    company: "AstraVision",
    mobile_phone: "07 8326 5402",
    email_address: "charlotte@astravision.io",
    postcode: "N17HZ",
    pay_later: false,
    pay_now: true,
  },
  {
    name: "Daniel Martin",
    company: "NeonBridge",
    mobile_phone: "07 6319 8230",
    email_address: "dan.martin@neonbridge.org",
    postcode: "OX19QA",
    pay_later: true,
    pay_now: true,
  },
  {
    name: "Amelia Thompson",
    company: "VectorForge",
    mobile_phone: "07 4291 4568",
    email_address: "amelia@vectorforge.net",
    postcode: "RM32TH",
    pay_later: false,
    pay_now: false,
  },
  {
    name: "Matthew Garcia",
    company: "QuantumShift",
    mobile_phone: "07 8492 7120",
    email_address: "matt.garcia@qshift.com",
    postcode: "DA17FX",
    pay_later: true,
    pay_now: false,
  },
  {
    name: "Harper Lewis",
    company: "VisionaryTech",
    mobile_phone: "07 6128 3447",
    email_address: "h.lewis@visionarytech.com",
    postcode: "CV58UY",
    pay_later: false,
    pay_now: true,
  },
  {
    name: "Joseph Walker",
    company: "FusionGrid",
    mobile_phone: "07 9317 2156",
    email_address: "joe.walker@fusiongrid.co",
    postcode: "BL27ZA",
    pay_later: true,
    pay_now: false,
  },
  {
    name: "Evelyn Robinson",
    company: "BrightPixel",
    mobile_phone: "07 4209 6753",
    email_address: "evelyn@brightpixel.org",
    postcode: "DE11QZ",
    pay_later: false,
    pay_now: false,
  },
  {
    name: "David Hall",
    company: "SynapseX",
    mobile_phone: "07 8213 4072",
    email_address: "david.h@synapsex.uk",
    postcode: "NE15YU",
    pay_later: true,
    pay_now: false,
  },
  {
    name: "Abigail Young",
    company: "CyberEdge Ltd",
    mobile_phone: "07 3984 1536",
    email_address: "abigail.young@cyberedge.com",
    postcode: "FY45QL",
    pay_later: false,
    pay_now: true,
  },
  {
    name: "Jackson King",
    company: "InfoStream Labs",
    mobile_phone: "07 5146 7681",
    email_address: "jackson.king@infostream.co.uk",
    postcode: "LS13NH",
    pay_later: true,
    pay_now: false,
  },
  {
    name: "Scarlett Wright",
    company: "Pathfinder Solutions",
    mobile_phone: "07 6351 2409",
    email_address: "scarlett@pathfinder.net",
    postcode: "BA28LK",
    pay_later: false,
    pay_now: false,
  },
  {
    name: "Logan Scott",
    company: "NexPhase Systems",
    mobile_phone: "07 2917 8795",
    email_address: "logan@nexphase.io",
    postcode: "PL38DU",
    pay_later: true,
    pay_now: true,
  },
  {
    name: "Grace Green",
    company: "PeakTech",
    mobile_phone: "07 3146 5539",
    email_address: "grace.green@peaktech.uk",
    postcode: "SR12FH",
    pay_later: false,
    pay_now: true,
  },
  {
    name: "Aiden Adams",
    company: "CoreNest",
    mobile_phone: "07 9812 6043",
    email_address: "aiden@corenest.com",
    postcode: "BT13PW",
    pay_later: false,
    pay_now: false,
  },
  {
    name: "Chloe Baker",
    company: "SkyTech Ventures",
    mobile_phone: "07 3462 8350",
    email_address: "chloe@skytechventures.com",
    postcode: "TR11WX",
    pay_later: true,
    pay_now: false,
  },
  {
    name: "Luke Nelson",
    company: "FlowSphere",
    mobile_phone: "07 5091 3652",
    email_address: "luke.nelson@flowsphere.net",
    postcode: "SP47GG",
    pay_later: false,
    pay_now: true,
  },
  {
    name: "Avery Hill",
    company: "QuantumLeap Tech",
    mobile_phone: "07 7358 2941",
    email_address: "avery@qleaptech.io",
    postcode: "BS23NR",
    pay_later: true,
    pay_now: false,
  },
  {
    name: "Sebastian Rivera",
    company: "MindWorks",
    mobile_phone: "07 8743 1859",
    email_address: "seb.rivera@mindworks.co.uk",
    postcode: "ME89PL",
    pay_later: false,
    pay_now: true,
  },
  {
    name: "Ella Campbell",
    company: "BrightEdge Ltd",
    mobile_phone: "07 3294 2078",
    email_address: "ella@brightedge.com",
    postcode: "GU19FR",
    pay_later: true,
    pay_now: false,
  },
  {
    name: "Liam Cox",
    company: "RedNova Ltd",
    mobile_phone: "07 6831 5447",
    email_address: "liam.cox@rednova.org",
    postcode: "TS78YT",
    pay_later: true,
    pay_now: true,
  },
  {
    name: "Zoey Gray",
    company: "Starline Systems",
    mobile_phone: "07 5982 4310",
    email_address: "zoey@starline.io",
    postcode: "WA31HZ",
    pay_later: false,
    pay_now: false,
  },
  {
    name: "Samuel Reed",
    company: "AetherCorp",
    mobile_phone: "07 8493 7761",
    email_address: "samuel.reed@aethercorp.com",
    postcode: "LE23JD",
    pay_later: false,
    pay_now: true,
  },
  {
    name: "Hannah Murphy",
    company: "NeuroNet",
    mobile_phone: "07 4136 9084",
    email_address: "hannah@neuronet.co.uk",
    postcode: "NR45ZL",
    pay_later: true,
    pay_now: false,
  },
  {
    name: "Nathan Ward",
    company: "MetaSphere Group",
    mobile_phone: "07 2487 5693",
    email_address: "nathan@metasphere.com",
    postcode: "KY67XZ",
    pay_later: false,
    pay_now: false,
  },
  {
    name: "Lily Cox",
    company: "TidalTech",
    mobile_phone: "07 7821 3206",
    email_address: "lily@tidaltech.io",
    postcode: "SO49RT",
    pay_later: true,
    pay_now: false,
  },
  {
    name: "Owen Price",
    company: "NanoWave",
    mobile_phone: "07 9312 1093",
    email_address: "owen.price@nanowave.net",
    postcode: "CH31UR",
    pay_later: false,
    pay_now: true,
  },
  {
    name: "Layla Wood",
    company: "HelixFlow",
    mobile_phone: "07 5243 6952",
    email_address: "layla@helixflow.com",
    postcode: "AB87PQ",
    pay_later: true,
    pay_now: false,
  },
  {
    name: "Gabriel Bell",
    company: "Incepta",
    mobile_phone: "07 3124 8672",
    email_address: "gabriel@incepta.org",
    postcode: "EH34MJ",
    pay_later: false,
    pay_now: true,
  },
  {
    name: "Nora Bennett",
    company: "Zenix Global",
    mobile_phone: "07 6532 3840",
    email_address: "nora@zenixglobal.com",
    postcode: "NG24QW",
    pay_later: false,
    pay_now: false,
  },
];
